name: Weekly Retrain Model

on:
  schedule:
    - cron: '0 7 * * 1'  # Every Monday at 07:00 UTC (03:00 Toronto)
  workflow_dispatch:      # Optional manual trigger

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python train_and_export.py

      - name: Commit updated model files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add models/*.pkl models/numeric_columns.json || true
          if ! git diff --cached --quiet; then
            git commit -m "Auto: weekly retrained model"
            git push
          else
            echo "No model changes to commit"
